apiVersion: v1
kind: Service
metadata:
  name: {{ include "jacob-p1.fullname" . }}-db
  labels:
    {{- include "jacob-p1.labels" . | nindent 4 }}
    role: db
spec:
  ports:
  - port: 5432
  selector:
    app.kubernetes.io/name: {{ include "jacob-p1.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    role: db
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: {{ include "jacob-p1.fullname" . }}-db-pv-claim
#   labels:
#     {{- include "jacob-p1.labels" . | nindent 4 }}
#     role: db
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
