apiVersion: v1
kind: Service
metadata:
  name: {{ include "jacob-p1.fullname" . }}-webapp
  labels:
    {{- include "jacob-p1.labels" . | nindent 4 }}
    role: webapp
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: 8080
  selector:
    {{- include "jacob-p1.selectorLabels" . | nindent 4 }}
    role: webapp
