version: '3'

services:
  jenkins:
    container_name: nick-jenkins
    image: nick-jenkins:latest
    build:
      dockerfile: jenkins.Dockerfile
      context: .
    ports:
    - 9077:8080
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
    - jenkins_home:/var/jenkins_home


volumes:
  jenkins_home:
    external: true
