# https://docs.microsoft.com/en-us/azure/aks/ingress-static-ip#create-a-ca-cluster-issuer
# https://cert-manager.io/docs/configuration/acme/#creating-a-basic-acme-issuer

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: nick.escalona@revature.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - http01:
        ingress:
          class: nginx
          podTemplate:
            spec:
              nodeSelector:
                "kubernetes.io/os": linux
